#!/usr/bin/sh

help() {
  echo "usage:"
  echo "  smallerbasic <filename> [-c <path-to-compiler-jar>] [-r <path-to-runtime>] [-o <output-dir>]"
  echo "  smallerbasic -h"
  echo ""
  echo "options:"
  echo "-c|--compiler"
  echo "  compiler location, overrides default ('APP')"
  echo "-r|--runtime"
  echo "  runtime location, overrides default ('RUNTIME')"
  echo "-o|--output"
  echo "  output directory without trailing slash, overrides default ('.')"
  echo "-h|--help"
  echo "  print this message"
  echo ""
}

# java bin (>= 16)
JAVA="java"
# default location of the compiler
APP="./app/build/libs/app.jar"
# where is the runtime llvm library
RUNTIME="./app/src/main/resources/runtime.ll"
# where all the artifacts will be put
OUTPUT_DIR="."
# LLVM optimizations
OPT="--mem2reg"

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
	help
	exit 0
fi

BASENAME=$(basename "$1" .sb)
DIRNAME=$(dirname "$1")
shift

while true
do
  case "${1}" in
    -r | --runtime)
      RUNTIME="${2}"
      shift 2
      ;;
    -c | --compiler)
      APP="${2}"
      shift 2
      ;;
    -o | --output)
      OUTPUT_DIR="${2}"
      shift 2
      ;;
    --|'')
      break
      ;;
    *)
      echo "unrecognized option '${1}'"
      help
      exit 1
      ;;
  esac
done

if [ ! -f "$APP" ]
then
  echo "Executable not found, run 'gradle jar'"
  exit 1
fi

if [ ! -f "$RUNTIME" ]
then
  echo "Runtime not found"
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

TEMP=$(mktemp --tmpdir="$OUTPUT_DIR" --suffix=".ll")
if $JAVA -jar "$APP" "$DIRNAME"/"$BASENAME".sb > "$TEMP"
then
  cat "$RUNTIME" "$TEMP" > "$OUTPUT_DIR"/"$BASENAME".ll
  rm "$TEMP"

  TEMP=$(mktemp --tmpdir="$OUTPUT_DIR" --suffix=".s")
  opt -opaque-pointers $OPT "$OUTPUT_DIR"/"$BASENAME".ll | llc -opaque-pointers > "$TEMP"
  clang "$TEMP" -lm -o "$OUTPUT_DIR"/"$BASENAME"
  rm "$TEMP"
  exit 0
else
  rm "$TEMP"
  exit 1
fi