#!/usr/bin/bash

JAVA="/usr/lib/jvm/openjdk17/bin/java"
APP="./app/build/libs/app.jar"
CC=clang
RUNTIME="./app/src/main/resources/runtime.ll" # TODO: clone it here in resources
BASENAME=$(basename "$1" .sb)
DIRNAME=$(dirname "$1")

if [ ! -f $APP ]
then
  echo "Executable not found, run 'gradle jar'"
  exit 1
fi

if [ ! -f $RUNTIME ]
then
  echo "Runtime not found"
  exit 1
fi

$JAVA -jar $APP "$DIRNAME"/"$BASENAME".sb | cat $RUNTIME - > "$BASENAME".ll
opt -opaque-pointers "$BASENAME".ll | llc -opaque-pointers -o "$BASENAME".s
$CC "$BASENAME".s -lm -o "$BASENAME"